\documentclass{article}
\usepackage{natbib}
\usepackage{hyperref}
\usepackage{bibentry}

\bibliographystyle{plainnat}
\setcitestyle{open={(},close={)}}

\author{EA30 -- Spring 2017}
\title{Annotated Bibliography}


\begin{document}
\maketitle
\nobibliography{Pb_literature}

\section{Abstract}



\tableofcontents

\section{Instructions}

Please complete the annotated bibliography by the 17th of April.


To help the readers, you might create subsection and even subsubsections, using \verb!\subsection{subsection name}! and \verb!\subsubsection{subsubsection name}!. 


\section{Industrial Sources (Khalil)}


\section{Use in Industry (except gasoline) (Caudia)}

\section{``Ethyl'' gas and airplane fuels (Viraj)}

\section{Atmospheric transport and deposition}
\begin{itemize}

\end{itemize}







\section{Aquatic transport (Olivia)}

\section{Sinks (Katie)}

\section{Food web dynamics (Mireya)}

\bibentry{cardwell_cd_2013}.
This study used empirical laboratory data, modeling, and field studies to determine whether lead is biomagnified in aquatic ecosystems. Cardwell et al. concluded that lead does not biomagnify through food chains consisting of primary producers, macroinvertebrates, and fish higher than trophic-level three. This study offers information contrary to that of Alexander et al., and furthers the debate regarding lead’s biomagnification potential. 

\bibentry{laskowski_are_1991}.
Laskowski’s paper, published in Oikos on behalf of the Department of Ecosystem Studies at Jagiellonian University, argues that biomagnification is not a shared property of all terrestrial ecosystems but rather something that varies dramatically based on an organism’s ability to process the substance.  The paper dismisses the role of biomagnification in poisoning larger mammals, claiming that more than three or four trophic levels are needed to accumulate a dangerous amount. I thought the article’s points on the subjectivity of biomagnfication was interesting, although I felt some of the larger conclusions were not grounded in enough evidence and were made hastily at the end. 

\bibentry{pinto_heavy_2003}.
Published in the Journal of Phycology, this paper finds that high levels of metal pollutants attack the chloroplast antioxidants in algae cells, eventually leading to their death. Algae are primary producers in the aquatic food chain and produce most the ocean’s oxygen; if algae are unable to perform their functions properly, a trophic cascade could wreak havoc on the entire food web.  

\bibentry{chen_accumulation_2000}.
This study, published in The Journal of Limnology and Oceanography, measured heavy metal concentrations in water, plankton, and fish from 20 lakes in watersheds across the United States. The study evaluates various factors that affect lead concentration in bodies of water, such as type of land use, water temperature, pH, etc. Notably, it stresses the need to evaluate higher and lower trophic levels separately, rather than attempt to understand them as the same metabolic mechanisms. The paper found that lead biodiminshed with trophic level, meaning bioaccumulation decreased with each energy transfer. 

\bibentry{dmello_food_2003}.
Chapter 9 in the book is title Heavy Metals and has a subsection on lead. The book offers some useful statistics, like how adults uptake 10\% of Pb from food, and children 50% (p. 211). It also touches upon the success of source-related lead phase-outs in food within the past decades. It will prove useful when evaluating how lead is ingested and absorbed by humans. 

\bibentry{islam_assessing_2007}.
Published in the Journal of Zhejiang University, this study evaluates the concentration of lead in agricultural crops. The study identifies multiple factors that may affect bioavailability of heavy metals in crops, such as fertilizer and crop rotation, while also highlighting the influence of root microbes on heavy metal uptake. The paper will be a useful in analyzing how lead enters human food systems and how agricultural practices can improve to prevent lead uptake. 

\bibentry{alexander_bioaccumulation_1999}.
Published in the Encyclopedia of Earth Science, this paper provides essential definitions for bioaccumulation, bioconcentration, and biomagnification. The paper is written for a scientific journal and employs a lot of biological terminology that may be inaccessible to some. The paper explains that heavy metals, such as lead, tend to bioaccumulate and then biomagnify because they pass through the lipid bilayer and cannot be easily dispelled by the body. 


\section{Toxicity (non-human) (Kelli)}

\section{Human health effects (physiological, toxicity) (Thea)}

\section{Public health effects (crime, IQ, etc) (Marissa)}



\end{document}

