\documentclass{article}
\usepackage{natbib}
\usepackage{hyperref}
\usepackage{bibentry}

\bibliographystyle{plainnat}
\setcitestyle{open={(},close={)}}

\author{EA30 -- Spring 2017}
\title{Annotated Bibliography}


\begin{document}
\maketitle
\nobibliography{Pb_literature}

\section{Abstract}



\tableofcontents

\section{Instructions}

Please complete the annotated bibliography by the 17th of April.

\subsection{Searching for Academic Sources}

There are numerous electronic sources to evaluate and obtain academic sources of information. Usually, we consider peer reviewed articles to have the highest quality scholarship. As a rule of thumb, this is a good start, but there is also a great deal of variation between sources, even journal titles can vary in quality. Thus, it's best to evaluate a range of sources and appreciate the subtle differences in quality and prestige.

First, you should search CUC databases using key words, such as Pb and lead. I admit the lead is tricky, because it's not a useful term due it a double meaning. I suggest heavy metals or trace metals with the other key words, i.e. fate and transport, toxicity, etc, depending on the topic you selected.

Below are links to some useful databases:

\begin{itemize}
  \item \href{http://apps.webofknowledge.com.ccl.idm.oclc.org/}{Web of Science}
  \item \href{http://www.jstor.org.ccl.idm.oclc.org/}{JStore}
  \item \href{https://scholar-google-com.ccl.idm.oclc.org/}{Google Scholar}
\end{itemize}


\subsection{Writing an Annotated Bibliography}

After adding your citation to the Pb\_literature.bib, using the BibTeX format, cite your reference using the syntax below. Then, write a concise annotation that summarizes the central theme and scope of the book or article. Include one or more sentences that (a) evaluate the authority or background of the author, (b) comment on the intended audience, (c) compare or contrast this work with another you have cited, or (d) explain how this work illuminates your bibliography topic.

\subsection{Implementing in \LaTeX}

\LaTeX is a software program used for desktop publishing. With an eye for detail, the program was developed to give the author a great deal of control. In contrast, Microsoft Word is designed to have lots of options, but these seem to get in the way of controlling the outcome. 

\LaTeX is an open source program and relies on specific formatting commands that begin with a backslash. For example to start a new section heading, we use \verb!\section{section name}! and \verb!\subsection{subsection name}! to create a subsection heading.

Below might be an example of what we are trying to accomplish using our Rstudio resources. The \LaTeX command for the citation is \verb!\bibentry{key}!, where key is identifies the citation based on the BibTeX citation entry as shown below.

However, we also need to add the citation to the *.bib file, in this case the file is called ``Pb\_literature.bib''. Open the file. You can see each entry within the curly brackets. Also, it starts with the definition of the entry, e.g. article, book, conference proceedings. We can easily add the citation using the databases cited above. All you need to do is search for the citation manager or citation tool and select a citation format ``bibtex''. Copy and paste the bibtex format (try to put it in the correct location, i.e. alphabetic order). Note the ``key'' is the first word after the citation definition. 

\subsection{Annotated Example}

\bigskip
\noindent \bibentry{barltrop1975absorption} . Summarizes important infomormation about Pb. This paper reviews work that span x years starting with early \ldots and noting recent information that includes \ldots. \cite{barltrop1975absorption} first describe xyz and how these issues have been largely \ldots.

\bigskip


To help the readers, you might create subsection and even subsubsections, using \verb!\subsection{subsection name}! and \verb!\subsubsection{subsubsection name}!. 


\section{Industrial Sources (Khalil)}


\section{Use in Industry (except gasoline) (Caudia)}

\section{``Ethyl'' gas and airplane fuels (Viraj)}

\section{Atmospheric transport and deposition}
\begin{itemize}
  \item \bibentry{cohan2010potential}
  \item \bibentry{blais1996using}
  \item \bibentry{cortizas2002atmospheric}
\end{itemize}







\section{Aquatic transport (Olivia)}

\section{Sinks (Katie)}

\section{Food web dynamics (Mireya)}

\bibentry{cardwell_cd_2013}.
This study used empirical laboratory data, modeling, and field studies to determine whether lead is biomagnified in aquatic ecosystems. Cardwell et al. concluded that lead does not biomagnify through food chains consisting of primary producers, macroinvertebrates, and fish higher than trophic-level three. This study offers information contrary to that of Alexander et al., and furthers the debate regarding lead’s biomagnification potential. 

\bibentry{laskowski_are_1991}.
Laskowski’s paper, published in Oikos on behalf of the Department of Ecosystem Studies at Jagiellonian University, argues that biomagnification is not a shared property of all terrestrial ecosystems but rather something that varies dramatically based on an organism’s ability to process the substance.  The paper dismisses the role of biomagnification in poisoning larger mammals, claiming that more than three or four trophic levels are needed to accumulate a dangerous amount. I thought the article’s points on the subjectivity of biomagnfication was interesting, although I felt some of the larger conclusions were not grounded in enough evidence and were made hastily at the end. 

\bibentry{pinto_heavy_2003}.
Published in the Journal of Phycology, this paper finds that high levels of metal pollutants attack the chloroplast antioxidants in algae cells, eventually leading to their death. Algae are primary producers in the aquatic food chain and produce most the ocean’s oxygen; if algae are unable to perform their functions properly, a trophic cascade could wreak havoc on the entire food web.  

\bibentry{chen_accumulation_2000}.
This study, published in The Journal of Limnology and Oceanography, measured heavy metal concentrations in water, plankton, and fish from 20 lakes in watersheds across the United States. The study evaluates various factors that affect lead concentration in bodies of water, such as type of land use, water temperature, pH, etc. Notably, it stresses the need to evaluate higher and lower trophic levels separately, rather than attempt to understand them as the same metabolic mechanisms. The paper found that lead biodiminshed with trophic level, meaning bioaccumulation decreased with each energy transfer. 

\bibentry{dmello_food_2003}.
Chapter 9 in the book is title Heavy Metals and has a subsection on lead. The book offers some useful statistics, like how adults uptake 10% of Pb from food, and children 50% (p. 211). It also touches upon the success of source-related lead phase-outs in food within the past decades. It will prove useful when evaluating how lead is ingested and absorbed by humans. 

\bibentry{islam_assessing_2007}.
Published in the Journal of Zhejiang University, this study evaluates the concentration of lead in agricultural crops. The study identifies multiple factors that may affect bioavailability of heavy metals in crops, such as fertilizer and crop rotation, while also highlighting the influence of root microbes on heavy metal uptake. The paper will be a useful in analyzing how lead enters human food systems and how agricultural practices can improve to prevent lead uptake. 

\bibentry{}

\bibentry{alexander_bioaccumulation_1999}.
Published in the Encyclopedia of Earth Science, this paper provides essential definitions for bioaccumulation, bioconcentration, and biomagnification. The paper is written for a scientific journal and employs a lot of biological terminology that may be inaccessible to some. The paper explains that heavy metals, such as lead, tend to bioaccumulate and then biomagnify because they pass through the lipid bilayer and cannot be easily dispelled by the body. 


\section{Toxicity (non-human) (Kelli)}

\section{Human health effects (physiological, toxicity) (Thea)}

\section{Public health effects (crime, IQ, etc) (Marissa)}



\end{document}

